### ISSUE TITLE
Open PyCon Pune Registration

### ISSUE THREAD

**Issue by kushaldas** [PyConPune/2017#8]
We will have to open up the registration.

**Comment by kushaldas** [comment]
All devsprint tickets are out.

**Comment by kushaldas** [comment]
Registration is live, we still have around 250 main conference tickets.

**Comment by sayanchowdhury** [comment]
Ticket Registration will close on 15th January 2017

**Comment by sayanchowdhury** [comment]
Ticket registration is closed now.
